var searchData=
[
  ['c_20applications_0',['Asynchrony - Add Asynchrony to Your C++ Applications',['../index.html',1,'']]],
  ['callback_20design_1',['Callback Design',['../usage_guide.html#bp_callbacks',1,'']]],
  ['callback_20exceptions_2',['Callback Exceptions',['../security.html#autotoc_md96',1,'']]],
  ['callback_20practices_3',['Callback Practices',['../security.html#autotoc_md89',1,'✅ Good Callback Practices'],['../security.html#autotoc_md90',1,'❌ Bad Callback Practices']]],
  ['callback_20security_4',['Callback Security',['../security.html#callback_security',1,'']]],
  ['capacity_5',['Resource Pool Capacity',['../security.html#autotoc_md95',1,'']]],
  ['checkin_6',['checkin',['../md_docs_2pages_2api.html#autotoc_md40',1,'checkin'],['../quick_reference.html#autotoc_md77',1,'checkout() / checkin()']]],
  ['checklist_7',['Security Checklist',['../security.html#security_checklist',1,'']]],
  ['checkout_8',['checkout',['../classsiddiqsoft_1_1resource__pool.html#a2eb2e2b5f122680c54aeb8b3508375c9',1,'siddiqsoft::resource_pool::checkout()'],['../md_docs_2pages_2api.html#autotoc_md39',1,'checkout']]],
  ['checkout_20checkin_9',['checkout() / checkin()',['../quick_reference.html#autotoc_md77',1,'']]],
  ['circular_20dependencies_10',['Circular Dependencies',['../security.html#autotoc_md91',1,'']]],
  ['clang_2010_11',['Clang 10+',['../getting_started.html#autotoc_md60',1,'']]],
  ['clear_12',['clear',['../classsiddiqsoft_1_1resource__pool.html#ab8874f3f51f8f1643a2d5ccbd55134c0',1,'siddiqsoft::resource_pool::clear()'],['../md_docs_2pages_2api.html#autotoc_md41',1,'clear'],['../quick_reference.html#autotoc_md79',1,'clear()']]],
  ['cmake_20recommended_13',['CMake Recommended',['../getting_started.html#autotoc_md56',1,'Using CMake (Recommended)'],['../index.html#autotoc_md67',1,'Using CMake (Recommended)']]],
  ['common_20issues_14',['Common Issues',['../quick_reference.html#qr_troubleshooting',1,'']]],
  ['common_20methods_15',['Common Methods',['../quick_reference.html#qr_methods',1,'']]],
  ['common_20patterns_16',['Common Patterns',['../md_docs_2pages_2api.html#autotoc_md43',1,'Common Patterns'],['../getting_started.html#common_patterns',1,'Common Patterns']]],
  ['comparison_20with_20alternatives_17',['Comparison with Alternatives',['../index.html#comparison',1,'']]],
  ['compilation_18',['Compilation',['../quick_reference.html#qr_compilation',1,'']]],
  ['compilation_20errors_19',['Compilation Errors',['../getting_started.html#autotoc_md65',1,'']]],
  ['compiler_20setup_20',['Compiler Setup',['../getting_started.html#compiler_setup',1,'']]],
  ['components_21',['Main Components',['../index.html#components',1,'']]],
  ['components_20at_20a_20glance_22',['Components at a Glance',['../quick_reference.html#qr_components',1,'']]],
  ['concepts_23',['Concepts',['../md_docs_2pages_2api.html#autotoc_md55',1,'']]],
  ['considerations_24',['Considerations',['../md_docs_2pages_2api.html#autotoc_md50',1,'Performance Considerations'],['../usage_guide.html#sp_performance',1,'Performance Considerations']]],
  ['constructor_25',['Constructor',['../md_docs_2pages_2api.html#autotoc_md5',1,'Constructor'],['../md_docs_2pages_2api.html#autotoc_md14',1,'Constructor'],['../md_docs_2pages_2api.html#autotoc_md23',1,'Constructor'],['../md_docs_2pages_2api.html#autotoc_md32',1,'Constructor']]],
  ['consumer_20pattern_26',['Producer-Consumer Pattern',['../examples.html#ex_producer_consumer',1,'']]],
  ['contents_27',['Table of Contents',['../md_docs_2pages_2api.html#autotoc_md1',1,'']]],
  ['control_28',['Queue Depth Control',['../security.html#autotoc_md94',1,'']]],
  ['copyright_29',['Copyright',['../index.html#copyright',1,'']]],
  ['count_30',['Count',['../usage_guide.html#sp_custom_threads',1,'Custom Thread Count'],['../usage_guide.html#rrp_custom_threads',1,'Custom Thread Count']]],
  ['critical_20exceptions_31',['Critical Exceptions',['../security.html#autotoc_md97',1,'']]],
  ['custom_20data_20types_32',['Custom Data Types',['../usage_guide.html#adv_custom_types',1,'']]],
  ['custom_20thread_20count_33',['Custom Thread Count',['../usage_guide.html#sp_custom_threads',1,'Custom Thread Count'],['../usage_guide.html#rrp_custom_threads',1,'Custom Thread Count']]]
];
