var searchData=
[
  ['recommended_0',['Recommended',['../getting_started.html#autotoc_md56',1,'Using CMake (Recommended)'],['../index.html#autotoc_md67',1,'Using CMake (Recommended)']]],
  ['reference_1',['Reference',['../md_docs_2pages_2api.html',1,'API Reference'],['../quick_reference.html',1,'Quick Reference']]],
  ['removecounter_2',['removeCounter',['../md_docs_2pages_2api.html#autotoc_md10',1,'removeCounter'],['../md_docs_2pages_2api.html#autotoc_md19',1,'removeCounter'],['../md_docs_2pages_2api.html#autotoc_md28',1,'removeCounter']]],
  ['reporting_3',['Vulnerability Reporting',['../security.html#vulnerability_reporting',1,'']]],
  ['request_20queue_4',['HTTP Request Queue',['../examples.html#ex_http_requests',1,'']]],
  ['requirements_5',['Requirements',['../index.html#requirements',1,'Requirements'],['../quick_reference.html#qr_requirements',1,'Requirements']]],
  ['resource_20exhaustion_20prevention_6',['Resource Exhaustion Prevention',['../security.html#resource_exhaustion',1,'']]],
  ['resource_20management_7',['Resource Management',['../quick_reference.html#autotoc_md83',1,'Example 4: Resource Management'],['../security.html#autotoc_md88',1,'Resource Management']]],
  ['resource_20pool_8',['Resource Pool',['../getting_started.html#autotoc_md64',1,'Pattern 4: Resource Pool'],['../quick_reference.html#qr_pattern_resource',1,'Resource Pool'],['../usage_guide.html#resource_pool',1,'Resource Pool']]],
  ['resource_20pool_20capacity_9',['Resource Pool Capacity',['../security.html#autotoc_md95',1,'']]],
  ['resource_20pool_20example_10',['Resource Pool Example',['../index.html#resource_example',1,'']]],
  ['resource_20pool_20methods_11',['Resource Pool Methods',['../usage_guide.html#rp_methods',1,'']]],
  ['resource_20pool_20operations_12',['Resource Pool Operations',['../security.html#autotoc_md99',1,'']]],
  ['resource_20pooling_20pattern_13',['Resource Pooling Pattern',['../md_docs_2pages_2api.html#autotoc_md46',1,'']]],
  ['resource_5fpool_14',['resource_pool',['../classsiddiqsoft_1_1resource__pool.html',1,'siddiqsoft::resource_pool&lt; T, InitCapacity &gt;'],['../classsiddiqsoft_1_1resource__pool.html#ab2f30543b6b4a81f832abbf37e0ec357',1,'siddiqsoft::resource_pool::resource_pool()=default'],['../classsiddiqsoft_1_1resource__pool.html#abaa39bcdca46579397fddd4ab8facf7f',1,'siddiqsoft::resource_pool::resource_pool(resource_pool &amp;)=delete'],['../classsiddiqsoft_1_1resource__pool.html#a1da5b82b5f0255e3f85e525c76038f66',1,'siddiqsoft::resource_pool::resource_pool(resource_pool &amp;&amp;src)=default'],['../md_docs_2pages_2api.html#autotoc_md35',1,'resource_pool'],['../quick_reference.html#autotoc_md74',1,'resource_pool&amp;lt;T&amp;gt;']]],
  ['resource_5fwrap_15',['resource_wrap',['../classsiddiqsoft_1_1resource__wrap.html',1,'siddiqsoft::resource_wrap&lt; T &gt;'],['../classsiddiqsoft_1_1resource__wrap.html#a16cc5bc7bb7264e87d7e1e538e6d8f02',1,'siddiqsoft::resource_wrap::resource_wrap()=delete'],['../classsiddiqsoft_1_1resource__wrap.html#a5e7272fcf105890309e7b9b56b885f9f',1,'siddiqsoft::resource_wrap::resource_wrap(T &amp;&amp;src, std::function&lt; void(T &amp;&amp;)&gt; &amp;&amp;f={})'],['../classsiddiqsoft_1_1resource__wrap.html#a67d8e730368112c5367996c21976403d',1,'siddiqsoft::resource_wrap::resource_wrap(const T &amp;)=delete']]],
  ['resources_16',['Additional Resources',['../security.html#security_resources',1,'']]],
  ['robin_20pool_17',['Robin Pool',['../quick_reference.html#qr_pattern_roundrobin',1,'Round-Robin Pool'],['../usage_guide.html#roundrobin_pool',1,'Round-Robin Pool']]],
  ['robin_20pool_20example_18',['Round-Robin Pool Example',['../index.html#roundrobin_example',1,'']]],
  ['robin_20vs_20simple_20pool_19',['Round-Robin vs Simple Pool',['../usage_guide.html#rrp_vs_simple',1,'']]],
  ['round_20robin_20pool_20',['Round Robin Pool',['../quick_reference.html#qr_pattern_roundrobin',1,'Round-Robin Pool'],['../usage_guide.html#roundrobin_pool',1,'Round-Robin Pool']]],
  ['round_20robin_20pool_20example_21',['Round-Robin Pool Example',['../index.html#roundrobin_example',1,'']]],
  ['round_20robin_20vs_20simple_20pool_22',['Round-Robin vs Simple Pool',['../usage_guide.html#rrp_vs_simple',1,'']]],
  ['roundrobin_5fpool_23',['roundrobin_pool',['../structsiddiqsoft_1_1roundrobin__pool.html',1,'siddiqsoft::roundrobin_pool&lt; T, N &gt;'],['../structsiddiqsoft_1_1roundrobin__pool.html#ada0325a6d61da0913204a7e4786d5ad6',1,'siddiqsoft::roundrobin_pool::roundrobin_pool(roundrobin_pool &amp;&amp;)=delete'],['../structsiddiqsoft_1_1roundrobin__pool.html#a37c8187ff48daf8a5c6609409b96261f',1,'siddiqsoft::roundrobin_pool::roundrobin_pool(roundrobin_pool &amp;)=delete'],['../structsiddiqsoft_1_1roundrobin__pool.html#a00d3146025ecfa8823259540c332fcf5',1,'siddiqsoft::roundrobin_pool::roundrobin_pool(std::function&lt; void(T &amp;&amp;)&gt; c)'],['../md_docs_2pages_2api.html#autotoc_md21',1,'roundrobin_pool'],['../md_docs_2pages_2api.html#autotoc_md52',1,'roundrobin_pool'],['../quick_reference.html#autotoc_md72',1,'roundrobin_pool&amp;lt;T, N&amp;gt;']]],
  ['rsrc_24',['rsrc',['../classsiddiqsoft_1_1resource__wrap.html#addd27484b1177a81e27d2f2f9ef617ff',1,'siddiqsoft::resource_wrap']]],
  ['runtime_20issues_25',['Runtime Issues',['../getting_started.html#autotoc_md66',1,'']]]
];
