var searchData=
[
  ['safety_0',['Safety',['../security.html#autotoc_md86',1,'Exception Safety'],['../security.html#autotoc_md84',1,'Memory Safety'],['../security.html#shutdown_safety',1,'Shutdown Safety'],['../md_docs_2pages_2api.html#autotoc_md48',1,'Thread Safety'],['../security.html#autotoc_md85',1,'Thread Safety'],['../security.html#thread_safety',1,'Thread Safety'],['../usage_guide.html#bp_threading',1,'Thread Safety'],['../security.html#autotoc_md87',1,'Type Safety']]],
  ['security_1',['Callback Security',['../security.html#callback_security',1,'']]],
  ['security_20checklist_2',['Security Checklist',['../security.html#security_checklist',1,'']]],
  ['security_20features_3',['Built-in Security Features',['../security.html#security_features',1,'']]],
  ['security_20guide_4',['Security Guide',['../security.html',1,'']]],
  ['see_20also_5',['See Also',['../index.html#see_also',1,'']]],
  ['serialization_6',['Serialization',['../security.html#autotoc_md102',1,'JSON Serialization'],['../usage_guide.html#adv_json_serialization',1,'JSON Serialization']]],
  ['setup_7',['Compiler Setup',['../getting_started.html#compiler_setup',1,'']]],
  ['shutdown_8',['Graceful Shutdown',['../security.html#autotoc_md100',1,'']]],
  ['shutdown_20safety_9',['Shutdown Safety',['../security.html#shutdown_safety',1,'']]],
  ['shutdown_20timeout_10',['Shutdown Timeout',['../security.html#autotoc_md101',1,'']]],
  ['simple_20async_20task_11',['Example 1: Simple Async Task',['../quick_reference.html#autotoc_md80',1,'']]],
  ['simple_20pool_12',['Simple Pool',['../usage_guide.html#rrp_vs_simple',1,'Round-Robin vs Simple Pool'],['../usage_guide.html#simple_pool',1,'Simple Pool']]],
  ['simple_20worker_13',['Simple Worker',['../usage_guide.html#simple_worker',1,'']]],
  ['simple_20worker_20example_14',['Simple Worker Example',['../index.html#simple_worker_example',1,'']]],
  ['simple_5fpool_15',['simple_pool',['../md_docs_2pages_2api.html#autotoc_md12',1,'simple_pool'],['../quick_reference.html#autotoc_md71',1,'simple_pool&amp;lt;T, N&amp;gt;'],['../md_docs_2pages_2api.html#autotoc_md51',1,'simple_worker vs simple_pool']]],
  ['simple_5fworker_16',['simple_worker',['../md_docs_2pages_2api.html#autotoc_md3',1,'simple_worker'],['../quick_reference.html#autotoc_md70',1,'simple_worker&amp;lt;T, Pri&amp;gt;']]],
  ['simple_5fworker_20vs_20simple_5fpool_17',['simple_worker vs simple_pool',['../md_docs_2pages_2api.html#autotoc_md51',1,'']]],
  ['single_20worker_18',['Single Worker',['../quick_reference.html#qr_pattern_worker',1,'']]],
  ['size_19',['size',['../md_docs_2pages_2api.html#autotoc_md8',1,'size'],['../md_docs_2pages_2api.html#autotoc_md17',1,'size'],['../md_docs_2pages_2api.html#autotoc_md26',1,'size'],['../md_docs_2pages_2api.html#autotoc_md38',1,'size'],['../quick_reference.html#autotoc_md78',1,'size()']]],
  ['start_20',['Quick Start',['../index.html#quickstart',1,'']]],
  ['started_21',['Getting Started',['../getting_started.html',1,'']]],
  ['steps_22',['Next Steps',['../getting_started.html#next_steps',1,'']]],
  ['studio_202019_20or_20later_23',['Visual Studio 2019 or later',['../getting_started.html#autotoc_md58',1,'']]],
  ['system_20monitoring_24',['System Monitoring',['../examples.html#ex_monitoring',1,'']]]
];
