var searchData=
[
  ['parallel_20processing_0',['Example 2: Parallel Processing',['../quick_reference.html#autotoc_md81',1,'']]],
  ['parameters_1',['Parameters',['../md_docs_2pages_2api.html#autotoc_md4',1,'Template Parameters'],['../md_docs_2pages_2api.html#autotoc_md13',1,'Template Parameters'],['../md_docs_2pages_2api.html#autotoc_md22',1,'Template Parameters'],['../md_docs_2pages_2api.html#autotoc_md31',1,'Template Parameters'],['../md_docs_2pages_2api.html#autotoc_md36',1,'Template Parameters'],['../quick_reference.html#qr_template_params',1,'Template Parameters']]],
  ['pattern_2',['Pattern',['../examples.html#ex_producer_consumer',1,'Producer-Consumer Pattern'],['../md_docs_2pages_2api.html#autotoc_md46',1,'Resource Pooling Pattern']]],
  ['pattern_201_3a_20fire_20and_20forget_3',['Pattern 1: Fire and Forget',['../getting_started.html#autotoc_md61',1,'']]],
  ['pattern_202_3a_20batch_20processing_4',['Pattern 2: Batch Processing',['../getting_started.html#autotoc_md62',1,'']]],
  ['pattern_203_3a_20periodic_20tasks_5',['Pattern 3: Periodic Tasks',['../getting_started.html#autotoc_md63',1,'']]],
  ['pattern_204_3a_20resource_20pool_6',['Pattern 4: Resource Pool',['../getting_started.html#autotoc_md64',1,'']]],
  ['patterns_7',['Patterns',['../quick_reference.html#qr_basic_patterns',1,'Basic Patterns'],['../md_docs_2pages_2api.html#autotoc_md43',1,'Common Patterns'],['../getting_started.html#common_patterns',1,'Common Patterns']]],
  ['performance_20considerations_8',['Performance Considerations',['../md_docs_2pages_2api.html#autotoc_md50',1,'Performance Considerations'],['../usage_guide.html#sp_performance',1,'Performance Considerations']]],
  ['performance_20tips_9',['Performance Tips',['../quick_reference.html#qr_performance',1,'Performance Tips'],['../usage_guide.html#bp_performance',1,'Performance Tips']]],
  ['periodic_20monitoring_10',['Example 3: Periodic Monitoring',['../quick_reference.html#autotoc_md82',1,'']]],
  ['periodic_20task_11',['Periodic Task',['../quick_reference.html#qr_pattern_periodic',1,'']]],
  ['periodic_20tasks_12',['Pattern 3: Periodic Tasks',['../getting_started.html#autotoc_md63',1,'']]],
  ['periodic_20worker_13',['Periodic Worker',['../usage_guide.html#pw_named',1,'Named Periodic Worker'],['../usage_guide.html#periodic_worker',1,'Periodic Worker']]],
  ['periodic_20worker_20example_14',['Periodic Worker Example',['../index.html#periodic_example',1,'']]],
  ['periodic_5fworker_15',['periodic_worker',['../md_docs_2pages_2api.html#autotoc_md30',1,'periodic_worker'],['../md_docs_2pages_2api.html#autotoc_md53',1,'periodic_worker'],['../quick_reference.html#autotoc_md73',1,'periodic_worker&amp;lt;Pri&amp;gt;']]],
  ['pool_16',['Pool',['../getting_started.html#autotoc_md64',1,'Pattern 4: Resource Pool'],['../quick_reference.html#qr_pattern_resource',1,'Resource Pool'],['../usage_guide.html#resource_pool',1,'Resource Pool'],['../quick_reference.html#qr_pattern_roundrobin',1,'Round-Robin Pool'],['../usage_guide.html#roundrobin_pool',1,'Round-Robin Pool'],['../usage_guide.html#rrp_vs_simple',1,'Round-Robin vs Simple Pool'],['../usage_guide.html#simple_pool',1,'Simple Pool'],['../quick_reference.html#qr_pattern_pool',1,'Thread Pool']]],
  ['pool_20capacity_17',['Resource Pool Capacity',['../security.html#autotoc_md95',1,'']]],
  ['pool_20example_18',['Pool Example',['../index.html#resource_example',1,'Resource Pool Example'],['../index.html#roundrobin_example',1,'Round-Robin Pool Example'],['../index.html#pool_example',1,'Thread Pool Example']]],
  ['pool_20methods_19',['Resource Pool Methods',['../usage_guide.html#rp_methods',1,'']]],
  ['pool_20operations_20',['Resource Pool Operations',['../security.html#autotoc_md99',1,'']]],
  ['pooling_20pattern_21',['Resource Pooling Pattern',['../md_docs_2pages_2api.html#autotoc_md46',1,'']]],
  ['practices_22',['Practices',['../usage_guide.html#best_practices',1,'Best Practices'],['../security.html#autotoc_md103',1,'Monitoring Best Practices'],['../security.html#autotoc_md89',1,'✅ Good Callback Practices'],['../security.html#autotoc_md90',1,'❌ Bad Callback Practices']]],
  ['prevention_23',['Prevention',['../security.html#deadlock_prevention',1,'Deadlock Prevention'],['../security.html#resource_exhaustion',1,'Resource Exhaustion Prevention']]],
  ['principles_24',['Design Principles',['../index.html#design',1,'']]],
  ['priority_25',['Priority',['../usage_guide.html#pw_priority',1,'Priority'],['../usage_guide.html#sw_priority',1,'Thread Priority']]],
  ['priority_20based_20workers_26',['Priority-Based Workers',['../examples.html#ex_priority_workers',1,'']]],
  ['processing_27',['Processing',['../examples.html#ex_event_processing',1,'Event Processing'],['../quick_reference.html#autotoc_md81',1,'Example 2: Parallel Processing'],['../examples.html#ex_file_processing',1,'File Processing'],['../getting_started.html#autotoc_md62',1,'Pattern 2: Batch Processing']]],
  ['producer_20consumer_20pattern_28',['Producer-Consumer Pattern',['../examples.html#ex_producer_consumer',1,'']]],
  ['program_29',['Your First Program',['../getting_started.html#first_program',1,'']]]
];
